### ISSUE TITLE
Key Error 'num_segments' and Name Error name 'ts' is no defined

### ISSUE THREAD

**Issue by UelisonSantos** [stanford-futuredata/InQuest#3]
Hello,

When running the current code, two errors appears for each dataset:

The first of them is on the key 'num_segments'

![image](https://github.com/stanford-futuredata/InQuest/assets/30526663/ec4a3d5c-d730-434c-bde1-6b0cf5710d7b)

The second one is on the key 'ts' 

![image](https://github.com/stanford-futuredata/InQuest/assets/30526663/463701c0-9b44-458f-8400-8bf8585e2610)

As a result, the code create the folders for each dataset, but doenst save the result files

The ts problem seems to be just missing the filename on the fuction.

**Comment by mdr223** [comment]
Hi there, apologies for the bugs, I tried cleaning up the repo around the time of submission but clearly missed a few things. I just pushed an update to the `main` branch which should hopefully address the issues you saw. If any other bugs arise please feel free to follow up here and I can take a look at them!

**Comment by UelisonSantos** [comment]
Hi!
I really appreciate your help in this matter. I am part of the Systems Group of TU Darmstadt. The idea is to use your paper as a start point of a lecture. 

I believe we are near to have a running version. We still have a problem with the write_json function.

![image](https://github.com/stanford-futuredata/InQuest/assets/30526663/2f35eaef-7748-40f4-a188-aed699633384)

It seems that the parameters are not matching the function: https://rdrr.io/github/skgrange/threadr/man/write_json.html
I can do more tests tomorrow, but I would appreciate your input on this.
Thank you!

**Comment by mdr223** [comment]
Oh wow that's great to hear! And apologies I didn't have a chance to fix this last night, but I just pushed a version which should write the config with the ts properly. Hopefully that's the last issue, and if I can help in any way with your lecture don't hesitate to ask!

**Comment by UelisonSantos** [comment]
Hi Matthew,

Thank you for the updates!

I am having a problem in the line 361 on simulator.py
results['median_rmse'] = results_df.compute_median_segment_error(lambda row: compute_median_segment_error, axis=1)

The code is trying to apply the function compute_median_segment_error to a dataframe, and returns an error.

**Comment by mdr223** [comment]
I'm running a potential fix now and I think it's working. Going to make sure the results look correct before I push -- but I should have a fix for you imminently!

**Comment by mdr223** [comment]
Okay, I've tested it and gotten the script to work on the first dataset. Just pushed the code changes!
